### ISSUE TITLE
Clarify "git pull the elkarte image to the src_html volume"

### ISSUE THREAD

**Issue by Frenzie** [Spuds/Docker-ElkArte#1]
I can do something like this:

```
docker run -it -v docker-elkarte_src_html alpine sh
```

And then git clone an Elkarte repo in there, but that doesn't seem to be persistent?

**Comment by Spuds** [comment]
That is the local volume outside of the docker container.  That way you can change the sources outside of the container with your editor of choice.  

Hummm that README could do with some improvements!   In your `docker-compose.yml` file you need to "complete" the volume section so that `src_html` actually points to a local (not docker) location.  So your volumes section will be something like:
```
volumes:
    db_data:
    src_html:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /my/sources
```

For me thats my NAS so its `/tank/github` So I can pull in a repo to a directory like `/tank/github/elkarte` and then the site is at `xxx.xxx.xxx.xxx/elkarte`  I have several dozen directorys under `/tank/github` and just use the directory name after the ip address of my NAS (or wherever you are running docker, could be as simple as localhost)
